 Given a 1D array, negate all elements which are between 3 and 8, in place (not created a new array).

In [30]:
import numpy as np
a = np.arange(10)
print (np.delete(a,np.s_[4:8],None))

[0 1 2 3 8 9]


Create random vector of size 10 and replace the maximum value by 0

In [29]:
b = np.random.randint(0,10,10)
b[np.argmax(b)] = 0
b

array([7, 0, 1, 2, 5, 7, 4, 6, 2, 4])

How to find common values between two arrays?


In [131]:
a = np.arange(0,10)
b = np.arange(5,15)
print(a)
print(b)
c = []
for i in a:
    if (b == a[i]).any() == True:
        c.append(a[i])
c

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


[5, 6, 7, 8, 9]

Reverse a vector (first element becomes last)


In [126]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Create a 3x3 matrix with values ranging from 0 to 8

In [38]:
d = np.random.randint(0,8,(3,3,3))
d

array([[[0, 0, 2],
        [7, 2, 5],
        [4, 5, 6]],

       [[3, 1, 1],
        [3, 0, 3],
        [1, 2, 0]],

       [[7, 7, 6],
        [5, 6, 3],
        [0, 1, 2]]])

Find indices of non-zero elements from the array [1,2,0,0,4,0]

In [43]:
arr = np.array([1,2,0,0,4,0])
print(np.where(arr>0))

(array([0, 1, 4], dtype=int64),)


Create a random vector of size 30 and find the mean value

In [48]:
a = np.random.randint(0,10,30) 
print(a.sum())

133


Create a 2d array with 1 on the border and 0 inside


In [87]:
a = np.zeros([10,10])
a[:1,:10]=a[:10,:1]=a[:,9]=a[9]=1
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Given an array x of 20 integers in the range (0, 100)

In [132]:
x = np.array(np.random.randint(0, 100, 20))
y = np.random.uniform(0, 20)
print (x)
print (y)
z = np.argmin(np.abs(x - y))
print("index need find is ",z)
print("value need find is ",x[z])


[70 69 26 99 14 60 69 10 40 85 67  2 28 56 79 34  8 22 49 74]
7.253640408313378
index need find is  16
value need find is  8
